### ISSUE TITLE
Hovering over a card in deck builder with pointer device should show image

### ISSUE THREAD

**Issue by alexmiddeleer** [mythgard-hub/mythgard-hub#182]
You should be able to use similar css hover code as we do on the /cards page.

**Comment by lily-pytel** [comment]
Is it supposed to have a little thumbnail or is it when hovering over the name? Or the entire row?

**Comment by PapaCapricorn** [comment]
> Is it supposed to have a little thumbnail or is it when hovering over the name? Or the entire row?

@lily-pytel For now I would say entire row. Thumbnails have been proposed, and they might co-exist (as they do on EWC). I'm not sure if you mean just including the card art, or are referring specifically to a smaller clickable hotspot area. Either way, in the short term just making the entire row is probably easiest, and would be my recommendation.
