### ISSUE TITLE
Deck search error message for input with spaces

### ISSUE THREAD

**Issue by alexmiddeleer** [mythgard-hub/mythgard-hub#186]
![image](https://user-images.githubusercontent.com/5400639/67135732-c1593100-f1ea-11e9-874f-865a24d07fdc.png)

We need to investigate this error and either fix it or prevent the user from entering spaces in the search. This might be a little bit tricky, or it might be trivial!

**Comment by Edswor** [comment]
I found the issue, its the filter query "to_tsvector('simple', deck.name) @@ to_tsquery('simple',deckName || ':*')" line 395 in postgress/init.sql
If you change to "plainto_tsquery" it does not give the error (but also does not find the deck).

For example if we want to find "norden aztlan" and we search with "norden az" it does not find it, so using only plainto_tsquery is not the final solution.

**Comment by Edswor** [comment]
Btw, I'm working on a fix.

**Comment by lily-pytel** [comment]
@Edswor sweet! I assigned you to the issue. Is there a PR for it?

**Comment by lily-pytel** [comment]
Sorry, clicked the wrong button. Didn't mean to close

**Comment by alexmiddeleer** [comment]
Fixed by #198
