### ISSUE TITLE
Footer floating ~15px off bottom on certian pages

### ISSUE THREAD

**Issue by YSavir** [mythgard-hub/mythgard-hub#193]
I'm seeing the footer float about 15px above the page bottom on certain pages:

* `/cards`
* `/deck-builder`

This is happening for me in both Chrome and Firefox on MacOS.

Screenshots:

<img width="1440" alt="Screen Shot 2019-10-23 at 8 32 49 AM" src="https://user-images.githubusercontent.com/5168781/67393362-396b8200-f570-11e9-9c66-0b41b499d886.png">
<img width="1440" alt="Screen Shot 2019-10-23 at 8 33 05 AM" src="https://user-images.githubusercontent.com/5168781/67393384-41c3bd00-f570-11e9-8c18-0988e2832581.png">
<img width="1440" alt="Screen Shot 2019-10-23 at 8 33 13 AM" src="https://user-images.githubusercontent.com/5168781/67393398-47b99e00-f570-11e9-9ecb-544a120b506b.png">

**Comment by alexmiddeleer** [comment]
@YSavir Thanks for the report!
