### ISSUE TITLE
Dynamic web previews for Cards and Decks

### ISSUE THREAD

**Issue by PapaCapricorn** [mythgard-hub/mythgard-hub#195]
- Web previews (ie: Open Graph properties) should display custom information specific to individual Card and Deck pages 

**- For Decks (see image for reference):** 
```
  <meta property="og:title" content="[Name of Deck] by [CreatorName]" />
  <meta property="og:site_name" content="Mythgard Hub" />
  <meta property="og:description" content="Standard Mythgard Deck, [BYRGOP], [#####] Essence, Updated [DD MMM YYYY]" />
  <meta property="og:url" content="https://mythgardhub.com/" />
  <meta property="og:type" content="article" />
  <meta property="og:image" content="https://cdn.mythgardhub.com/identity/og-image.jpg" />
  <meta property="og:image:type" content="image/png" />
```
![WebPreview-Decks](https://user-images.githubusercontent.com/39966530/67423435-4903be80-f5a2-11e9-8278-e42e14ecb5f3.jpg)

**- For Cards (see image for reference):** 
```
  <meta property="og:title" content="[Card Name] | Mythgard Hub" />
  <meta property="og:site_name" content="Mythgard Hub" />
  <meta property="og:description" content="[Faction], #[Mana Cost]X[Influence Cost] [Rarity] [Type], [Subtype], [Set]" />
  <meta property="og:url" content="https://mythgardhub.com/" />
  <meta property="og:type" content="article" />
  <meta property="og:image" content="https://s3-us-west-2.amazonaws.com/cards.mythgardhub.com/core/[CardName].png" />
  <meta property="og:image:type" content="image/png" />
```
![WebPreview-Card](https://user-images.githubusercontent.com/39966530/67423575-810b0180-f5a2-11e9-8b5d-575a4b3c654a.jpg)

**Comment by Edswor** [comment]
I'm currently implementing this.

**Comment by alexmiddeleer** [comment]
@Edswor were you planning to add OG fields for the card page as well, or would you like us to split that off to a new issue?

**Comment by Edswor** [comment]
The card page should have the OG fields. I added to both deck and card page.

**Comment by alexmiddeleer** [comment]
@Edswor Ah yes, totally missed it. Thanks. We're having some issues seeing the OG fields in discord, perhaps an issue with server side rendering with Next.js. Looking into it now. ping me on discord if you have any thoughts.

**Comment by Edswor** [comment]
The pull request #224 should fix this.

**Comment by alexmiddeleer** [comment]
This work is complete. Thanks again for all your hard work @Edswor !
