### ISSUE TITLE
Track and display page views for deck pages

### ISSUE THREAD

**Issue by PapaCapricorn** [mythgard-hub/mythgard-hub#202]
- Track number of views for individual deck pages

- Display page views on the info column for the corresponding deck (see [image](https://user-images.githubusercontent.com/39966530/67644169-5055ff80-f8f5-11e9-95a5-4df6833a5ffe.png) for reference)

- [Link to mockup](https://mythgard-hub.github.io/saved_deck_template.html)

- [Eyeball icon](https://cdn.mythgardhub.com/icons/eyeball.svg) can be found on AWS

- Eventually we may decide to restrict this to unique page views but that can wait if it is more difficult

![image](https://user-images.githubusercontent.com/39966530/67644169-5055ff80-f8f5-11e9-95a5-4df6833a5ffe.png)

**Comment by lily-pytel** [comment]
Completed in #272
