### ISSUE TITLE
Display DECKS section banner on individual deck pages

### ISSUE THREAD

**Issue by PapaCapricorn** [mythgard-hub/mythgard-hub#203]
- Display sectional banner on individual deck pages, including image and DECKS title found on [top level decks page](https://www.mythgardhub.com/decks) to improve site navigation and wayfinding

- Currently, individual deck pages ([example](https://www.mythgardhub.com/deck?id=634)) do not display the sectional banner, unlike sub-level pages in other site sections for example [individual Card pages](https://www.mythgardhub.com/card?id=1) or [Events result listings](https://www.mythgardhub.com/event?id=3)

- [Reference image](https://user-images.githubusercontent.com/39966530/67645066-dcb7f080-f8fc-11e9-8e4c-309108928927.png)

- [Link to mockup](https://mythgard-hub.github.io/saved_deck_upvoted_template.html)

- See also related issue: [Add links to top level section pages from title banners](https://github.com/mythgard-hub/mythgard-hub/issues/204)

![image](https://user-images.githubusercontent.com/39966530/67645066-dcb7f080-f8fc-11e9-8e4c-309108928927.png)

**Comment by Edswor** [comment]
Added the changes in the pull request 199 (https://github.com/mythgard-hub/mythgard-hub/pull/199)

**Comment by lily-pytel** [comment]
Thank you for doing this!
