### ISSUE TITLE
Add links to top level section pages from title banners

### ISSUE THREAD

**Issue by PapaCapricorn** [mythgard-hub/mythgard-hub#204]
- Image and text in title banners on sub level pages should link to the top level section page as a secondary means of navigation

- For example, clicking the image or the word CARDS on the banner of the [Foul Harvest card page](https://www.mythgardhub.com/card?id=2) should link back to the [top level Cards section page](https://www.mythgardhub.com/cards) 

- See [image](https://user-images.githubusercontent.com/39966530/67645124-315b6b80-f8fd-11e9-8f49-147a2f836a1e.png) for reference

- See also related issue: [Display DECKS section banner on individual deck pages](https://github.com/mythgard-hub/mythgard-hub/issues/203)

![image](https://user-images.githubusercontent.com/39966530/67645124-315b6b80-f8fd-11e9-8f49-147a2f836a1e.png)

**Comment by wajeehsheikh** [comment]
HI, 
I would like to help out with this issue.
Thanks,
Waj

**Comment by PapaCapricorn** [comment]
Hi Wajeeh -

Thanks for your interest. Are you on the Mythgard Hub Discord server?

If not you can join here: https://discord.gg/RBX3zeG

Cheers,
PapaC

**Comment by YSavir** [comment]
To clarify, is someone working on this issue already?

If not, I'd be glad to take on it. As someone new to Next, it's a great intro. I've actually already started on it just as a way to familiarize myself with the codebase, even if someone else has the feature ready. Glad to submit a PR if it's still needed, though!

- Yaniv (AKA Hansolite on Discord)

**Comment by lily-pytel** [comment]
@YSavir no one has claimed it yet, so feel free to assign yourself to it and set it to in progress. Thank you for helping!

**Comment by YSavir** [comment]
@lily-pytel Great! The assignees section doesn't allow me to add myself--is there another way I can go about that?

**Comment by lily-pytel** [comment]
@YSavir added you!

**Comment by alexmiddeleer** [comment]
@YSavir What's your discord handle if you want the contributor designation?
