### ISSUE TITLE
Display rarity indicator on card rows in decklist

### ISSUE THREAD

**Issue by PapaCapricorn** [mythgard-hub/mythgard-hub#216]
Display a 7px wide column at the right end of card rows in a decklist with color indicating card rarity using the following colors:

- Common: #926950

- Uncommon: #A5A5A5

- Rare: #FDF007

- Mythic: #33A0E0

For reference, see **[Deck list mockup](https://mythgard-hub.github.io/saved_deck_template.html)**

![image](https://user-images.githubusercontent.com/39966530/68435694-f8878600-0189-11ea-8962-c6b53fa0a26f.png)

**Comment by Edswor** [comment]
I can do this.

**Comment by Edswor** [comment]
Added the pull request #217 for this change
