### ISSUE TITLE
Lack of padding in margins on home page

### ISSUE THREAD

**Issue by alexmiddeleer** [mythgard-hub/mythgard-hub#221]
![image](https://user-images.githubusercontent.com/5400639/68821768-2b83bb00-065d-11ea-90fe-35ec6ffbc898.png)

As shown in the screenshot, at least on Chrome on my macbook, the home page margins seem to have disappeared.

**Comment by lily-pytel** [comment]
My fault when I decreased the margins to have more space in the deck builder. Will fix.
